> sample(x = 1:6, size = 20, replace = TRUE)
[1] 1 1 1 6 2 2 4 5 4 3 1 3 6 6 5 2 2 6 2 3
> # This line of code allows R to generate 20 random outcomes from a sample containing 6 different variables (labelled as numerical characters from 1 to 6).
  > # "Replace = TRUE" means that each number can be drawn more than once, simulating what rolling a die would be like. 
  > # R randomly generated the sample above, in which the number 6 appears 4 times. 
  > 1/6
[1] 0.1666667
> 4/20
[1] 0.2
> # Theoretically, the probability of getting a 6 after rolling a fair die is 0.1666667, however the result we got from the numbers generated by R gives us a slighly higher experimental probability of 0.2. But still pretty close from the expected value of 3.33 given by 
  > 1/6 * 20
[1] 3.333333